package entities;

public enum TipPersonalMedical {
	MEDICI, MEDICI_DE_FAMILIE, DENTISTI, FARMACISTI, FIZIOKINETO, FIZIOTERAPEUTI, ASISTENTI_STUDII, ASISTENTI_MED_GEN, ALT_PERSONAL, 
	SANITAR_MEDIU, ASISTENT_MEDICAL, MOASE, ASISTENT_FIZIOKINETO, ASISTENT_FIZIO, PERSONAL_AUXILIAR
}
